### ISSUE TITLE
Message send status in wrong position

### ISSUE THREAD

**Issue by paresh-navadiya** [rcmcastro/whatsapp-ios#2]
Firstly i want to thank you for your great work. As i was checking sample i came across this issue as i believe this is a issue or wanted like this.

![ios simulator screen shot 06-jul-2015 3 30 25 am](https://cloud.githubusercontent.com/assets/1125736/8517481/6ac0976c-238f-11e5-9601-3cd48edb8070.png)

**Comment by rcmstark** [comment]
Yeah, it's. I just commit a new version fixing it. Thanks for the compliment.
