### ISSUE TITLE
Message Text Alignment

### ISSUE THREAD

**Issue by beat843796** [rcmcastro/whatsapp-ios#3]
I think it would be better if textalignment for sender and receiver is left.

**Comment by rcmstark** [comment]
Hi @beat843796, I don't set text alignment in my UITableViewCell for the chat text. I just checked on xcode, and the default alignment value for UILabels and UITextView is left.

Can you send a picture of this issue?

**Comment by beat843796** [comment]
see sender screenshot attached, this is right text alignment. on imessage and whatsapp its left and in your implementation its right.
![bildschirmfoto 2015-07-29 um 12 58 33](https://cloud.githubusercontent.com/assets/433430/8955945/a3f619de-35f1-11e5-80c5-2e6ccd1b726b.jpeg)

**Comment by rcmstark** [comment]
lol. This is a pretty old picture of the project. I changed it a long time ago. Try to run the project and see =)

**Comment by beat843796** [comment]
oh im sorry...

**Comment by rcmstark** [comment]
It's ok, My bad keep this old picture =)
