### ISSUE TITLE
Load earlier message header and unread message count header  missing

### ISSUE THREAD

**Issue by maradkar** [rcmcastro/whatsapp-ios#4]
I have added this library, I found this is very useful to me, In my chatting application, I am facing one problem while adding 100 of message app getting stuck, so could you please update this library for same, it will very useful all developer.

**Comment by rcmstark** [comment]
@maradkar  So when you add 100 messages it crash? What happen exactly?

**Comment by rcmstark** [comment]
No response, closing it
