### ISSUE TITLE
Integration with Quickblox

### ISSUE THREAD

**Issue by toftof** [rcmcastro/whatsapp-ios#5]
Hey Rafael, By any chance you can integrate this with QuickBlox or any other chat APIs? This control is just awesome. It would be even more useful if it is readily available with chat providers. This is not an issue. You can regard it as a wish list from me. Cheers!

**Comment by rcmstark** [comment]
Hi @toftof, I created a framework with this controller and I'm using with my REST API for Chat. I'm still working on it and when I finish I will update the full code here. This controller is just 20% of the framework =)

**Comment by rcmstark** [comment]
I'm using Google AppEngine for backend. I don't have plans for QuickBlox.
