### ISSUE TITLE
Error when dragging up in the message viewcontroller

### ISSUE THREAD

**Issue by devidasm** [rcmcastro/whatsapp-ios#7]
Whatsapp[7544:125074] **\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [50 nan]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00935746 **exceptionPreprocess + 182
    1   libobjc.A.dylib                     0x005bca97 objc_exception_throw + 44
    2   CoreFoundation                      0x0093566d +[NSException raise:format:] + 141
    3   QuartzCore                          0x04f0f6ae _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 190
    4   QuartzCore                          0x04f0f85c -[CALayer setPosition:] + 56
    5   QuartzCore                          0x04f0ffa2 -[CALayer setFrame:] + 754
    6   UIKit                               0x00f86f89 -[UIView(Geometry) setFrame:] + 331
    7   UIKit                               0x010c9d72 -[UIImageView _setViewGeometry:forMetric:] + 228
    8   UIKit                               0x010c9f7a -[UIImageView setFrame:] + 63
    9   UIKit                               0x00f88f77 -[UIView(Geometry) _applyAutoresizingMaskWithOldSuperviewSize:] + 967
    10  UIKit                               0x00f89cd6 -[UIView(Geometry) _resizeWithOldSuperviewSize:] + 301
    11  UIKit                               0x00f89d63 -[UIView(Geometry) resizeWithOldSuperviewSize:] + 121
    12  UIKit                               0x00f88893 __46-[UIView(Geometry) resizeSubviewsWithOldSize:]_block_invoke + 87
    13  CoreFoundation                      0x00859cc3 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 99
    14  CoreFoundation                      0x0085935f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 239
    15  UIKit                               0x00f88823 -[UIView(Geometry) resizeSubviewsWithOldSize:] + 149
    16  UIKit                               0x00f87089 -[UIView(Geometry) setFrame:] + 587
    17  UIKit                               0x00fa905a -[UIScrollView setFrame:] + 224
    18  UIKit                               0x017230aa -[UITextView setFrame:] + 394
    19  Whatsapp                            0x000ae5c1 -[MessageCell setTextView] + 417
    20  Whatsapp                            0x000ae380 -[MessageCell buildCell] + 48
    21  Whatsapp                            0x000ae2eb -[MessageCell setMessage:] + 107
    22  Whatsapp                            0x000b9453 -[MessageController tableView:cellForRowAtIndexPath:] + 339
    23  UIKit                               0x0103673d -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 473
    24  UIKit                               0x0103681f -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 77
    25  UIKit                               0x0100e8c3 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2770
    26  UIKit                               0x01029d70 -[UITableView layoutSubviews] + 220
    27  UIKit                               0x00f9c57a -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 668
    28  libobjc.A.dylib                     0x005d2771 -[NSObject performSelector:withObject:] + 70
    29  QuartzCore                          0x04f18e47 -[CALayer layoutSublayers] + 144
    30  QuartzCore                          0x04f0c925 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 403
    31  QuartzCore                          0x04f0c77a _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
    32  QuartzCore                          0x04e68c52 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 284
    33  QuartzCore                          0x04e6a0e5 _ZN2CA11Transaction6commitEv + 487
    34  QuartzCore                          0x04f4216d _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 477
    35  QuartzCore                          0x04f425ab _ZN2CA7Display16TimerDisplayLink8callbackEP16__CFRunLoopTimerPv + 123
    36  CoreFoundation                      0x0088e866 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 22
    37  CoreFoundation                      0x0088e1ed __CFRunLoopDoTimer + 1309
    38  CoreFoundation                      0x0084c54a __CFRunLoopRun + 2090
    39  CoreFoundation                      0x0084ba5b CFRunLoopRunSpecific + 443
    40  CoreFoundation                      0x0084b88b CFRunLoopRunInMode + 123
    41  GraphicsServices                    0x04a362c9 GSEventRunModal + 192
    42  GraphicsServices                    0x04a36106 GSEventRun + 104
    43  UIKit                               0x00f09106 UIApplicationMain + 1526
    44  Whatsapp                            0x000b7cea main + 138
    45  libdyld.dylib                       0x02eedac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by rcmstark** [comment]
Hi, can you reproduce your actions to generate this crash?
